### PR TITLE
Merge origin with react 0.14

### PR DESCRIPTION
**Pull request by albertfdp**

### CODE REVIEW

**Comment by dmatteo** [comment]
uh?

**Comment by albertfdp** [comment]
`this.props.children.map` ==> https://facebook.github.io/react/docs/top-level-api.html#react.children.map
https://github.com/podio/react-simpletabs/blob/master/lib/react-simpletabs.jsx#L86

Working on a PR for that

**Comment by dmatteo** [comment]
That's cool, but what are all the other commits?

**Comment by dmatteo** [comment]
@albertfdp we're not using this component anymore.
I'm going to delete the fork

**Pull request closed without merging**
